# Generated by Django 2.2.1 on 2019-05-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spis_tel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='osoba',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='emaile', to='spis_tel.Osoba'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='osoba',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='telefony', to='spis_tel.Osoba'),
        ),
    ]
