# Generated by Django 2.2.1 on 2019-05-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spis_tel', '0003_auto_20190519_1150'),
    ]

    operations = [
    ]
