# Generated by Django 2.2.1 on 2019-05-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spis_tel', '0004_auto_20190519_1152'),
    ]

    operations = [
    ]
