# Generated by Django 2.2.1 on 2019-05-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spis_tel', '0006_auto_20190519_1202'),
    ]

    operations = [
    ]
